spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/trevbol
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jhostyn802@gmail.com
spring.mail.password=gmxcikjbyaqntmod


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

admin.username=admin
admin.password=admin123